// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCngj8Xc3XRgr2c119i7x-K5kx93iFPruA',
    appId: '1:313457111182:web:00b60046a2cb74aa1659df',
    messagingSenderId: '313457111182',
    projectId: 'technews-1b0f7',
    authDomain: 'technews-1b0f7.firebaseapp.com',
    storageBucket: 'technews-1b0f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCICW3tviXvmhTKgo-HaOxFuYhLKNpHU9E',
    appId: '1:313457111182:android:f9f51555dae865881659df',
    messagingSenderId: '313457111182',
    projectId: 'technews-1b0f7',
    storageBucket: 'technews-1b0f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKglO-YqRz1S_-YH_HiFL7D-uKgHkxN_s',
    appId: '1:313457111182:ios:e7c873a3e1fca8611659df',
    messagingSenderId: '313457111182',
    projectId: 'technews-1b0f7',
    storageBucket: 'technews-1b0f7.appspot.com',
    iosBundleId: 'com.example.technews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKglO-YqRz1S_-YH_HiFL7D-uKgHkxN_s',
    appId: '1:313457111182:ios:e7c873a3e1fca8611659df',
    messagingSenderId: '313457111182',
    projectId: 'technews-1b0f7',
    storageBucket: 'technews-1b0f7.appspot.com',
    iosBundleId: 'com.example.technews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCngj8Xc3XRgr2c119i7x-K5kx93iFPruA',
    appId: '1:313457111182:web:24dd73851672c5271659df',
    messagingSenderId: '313457111182',
    projectId: 'technews-1b0f7',
    authDomain: 'technews-1b0f7.firebaseapp.com',
    storageBucket: 'technews-1b0f7.appspot.com',
  );
}
